name: Vue Wechat Login
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          ref: main
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Use Yarn
        run: npm install -g yarn
      - name: Lint
        run: |
          yarn install
          yarn lint
