name: Vue Wechat Login
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '22' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          ref: main
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Use Pnpm
        run: npm install -g pnpm
      - name: Lint
        run: |
          pnpm install
          pnpm lint
